version: "3.7"

services:
    ui:
        container_name: CVFrontend
        build:
            context: .
        volumes:
            - "./ui:/app"
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
